server:
  port: 8081

spring:
  profiles:
    default: staging

welcome:
  message: Dev environment!

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,beans,scheduledtasks'
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true